name: playx_core
description: Core package for playx eco system contains shared classes and utilities.
version: 0.7.4
homepage: https://sourcya.io/
repository: https://github.com/playx-flutter/playx_core
issue_tracker: https://github.com/playx-flutter/playx_core/issues
topics:
  - playx
  - ecosystem
  - core
  - prefs
  - env

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  sprintf: ^7.0.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  get_it: ^9.0.5
  worker_manager: ^7.2.7
  talker_logger: ^5.0.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
